import './LoginModel';
import './RegModel';
import './SettingsModel';
import './ProfileModel';
import './sendPostModel';
import './LogoutModel';
import './UserModel';
import './createAlbum';
import './addPhotosModel';
import './MediaAlbumsModel'
import './MediaPhotosModel'
import './friendsModel'
import './singlePostModel'
import './createDialogModel'
import './dialogModel'
import './groupModel'
import './singleGroupModel'
